#add_newline = false

[directory]
truncate_to_repo = false
style = "#deb887"

[git_branch]
symbol = "ğŸŒ± "
style = "#00ff7f"

[git_commit]
#disabled = true
#commit_hash_length = 4

[git_status]
conflicted = " C"
ahead = " ah"
behind =  "bh"
diverged = " div"
untracked = " U"
stashed = " S"
modified = " M"
staged.value = " +"
staged.style = "green"
staged_count.enabled = true
staged_count.style = "green"
renamed = " reN"
deleted = " D"
format = '([\[$all_status$ahead_behind \] ]($style) )' #format = " ]"
style = "red"

[character]
success_symbol = "[â¯](#00ff7f)"
error_symbol = "[â¯](bold red)"
vicmd_symbol = "[â®](bold gr`een)"

[memory_usage]
disabled = false
show_percentage = true
show_swap = true
threshold = -1
separator = "|"
style = "bold dimmed green"

[package]
disabled = true
format =" "
