[tools]
bat = "latest"
"nix:mcfly" = "latest"
"nix:tldr" = "latest"
"nix:htop" = "latest"
fd = "latest"
lefthook = "latest"
jq = "latest"
starship = "latest"
delta = "latest"
typos = "latest"
rg = "latest"
zoxide = "latest"
fzf = "latest"
"nix:mcfly-fzf" = "latest"
helix = "latest"
# gcloud = "552.0.0"
"nix:tenv" = "latest"
eza = "latest"
argc = "latest"
dust = "latest"
zellij = "latest"
lazygit = "latest"
ctop = "latest"
dotenvx = "latest"
yazi = "latest"
jnv = "latest"
yq = "latest"
terraform-ls = "latest"
node = "latest"
jj = "latest"

[settings]
experimental = true
